### ISSUE TITLE
 knn-per trainings are the same

### ISSUE THREAD

**Issue by eepLearning** [omarfoq/knn-per#3]
Hello. 
Thanks for the clean and excellent code, @omarfoq.
One question is, except for evaluation, is knn-per training not different from FedAvg's?
Best Regard

**Comment by omarfoq** [comment]
Hello @eepLearning, 

Yes you are right, in most of our experiments the global model used by kNN-Per is trained by all clients through FedAvg (see Section 5 in the paper). However, it is possible to train the global model using other algorithms. For example, in order to obtain Figure 3 (in the paper), we train a global model for CIFAR-10, in a centralized way, and we save the weights at different stages of the training, leading to global models with different accuracy. 

Note that you can use any algorithm, e.g., SCAFFOLD, or  FedProx, to train the global model, by minor modifications to our code base.   

I hope this answers your question, please let me know if you have additional questions.

**Comment by eepLearning** [comment]
Thank you so much for the quick and clear reply. 
All my questions have been resolved.
